/var/spool/slurmd/job333972/slurm_script: line 25: /home/ids/jpabon/anaconda3/etc/profile.d/conda.sh: No such file or directory

CondaError: Run 'conda init' before 'conda activate'

/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
Traceback (most recent call last):
  File "/home/ids/jpabon/projects/clip_odg/main.py", line 13, in <module>
    from utils.metrics import calculate_metrics
  File "/home/ids/jpabon/projects/clip_odg/utils/metrics.py", line 2, in <module>
    from sklearn.metrics import accuracy_score, f1_score
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 15, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/sklearn/utils/_array_api.py", line 14, in <module>
    import scipy.special as special
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/scipy/special/__init__.py", line 826, in <module>
    from . import _basic
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/scipy/special/_basic.py", line 22, in <module>
    from ._multiufuncs import (assoc_legendre_p_all,
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/scipy/special/_multiufuncs.py", line 142, in <module>
    sph_legendre_p = MultiUFunc(
  File "/home/ids/jpabon/miniconda3/envs/clip_odg/lib/python3.10/site-packages/scipy/special/_multiufuncs.py", line 41, in __init__
    raise ValueError("All ufuncs must have type `numpy.ufunc`."
ValueError: All ufuncs must have type `numpy.ufunc`. Received (<ufunc 'sph_legendre_p'>, <ufunc 'sph_legendre_p'>, <ufunc 'sph_legendre_p'>)
srun: error: nodemm06: task 0: Exited with exit code 1
